[IV 21-22] Objetivo 4
Paszser/ComparerApp pull request #21
Opened 2021-11-11 07:37 UTC by Paszser

2021-11-24 16:15 UTC, Paszser commented
Lista para revisión @JJ

2021-11-28 11:11 UTC, JJ requested changes
Ninguno de los commits se refiere a ningún issue (que aparentemente no se han creado). Mira [la lista de comprobación](https://jj.github.io/IV/documentos/proyecto/4.Tests#lista-de-comprobaci%C3%B3n) antes de volver a ponerlo como listo para revisión.

2021-11-30 16:53 UTC, Paszser commented
@JJ Incluidos los commit del código que referencian el issue creado(desde dónde se hace una referencia a la HU correspondiente) que trata de resolver lo planteado en el objetivo. Listo para revisión.

2021-12-01 07:00 UTC, JJ requested changes
Comprueba lo hecho frente a la lista de comprobación de este objetivo y los errores frecuentes antes de ponerlo para revisión de nuevo.

2021-12-01 07:00 UTC, JJ commented on spec/spec_helper.rb
> +# This file was generated by the `rspec --init` command. Conventionally, all
Ningún fichero generado en el repo

2021-12-01 07:00 UTC, JJ commented on spec/videojuego_spec.rb
> +        lista.each do |(llave, valor)|
ESto tampoco testea la lógica de negocio.

2021-12-07 16:58 UTC, JJ requested changes
NO hay ninguna lógica de negocio, ni ningún test de la misma.

2021-12-07 16:58 UTC, JJ commented on docs/testrunner.md
> +## Elección
Nunca pedimos que me cuentes lo que has elegido. Lo que necesito es saber los criterios que has seguido, y qué hace a esa herramienta más adecuada que otras.

2021-12-07 16:58 UTC, JJ commented on lib/tienda_web.rb
> +            return prediccion_final
A ver si lo he entendido. ¿Tu lógica de negocio consiste en ordenar? Si es así, no es una lógica de negocio. Tampoco sé muy bien como ordenando llevas a cabo una predicción.

2021-12-07 16:58 UTC, JJ commented on lib/videojuego.rb
>      class Videojuego
¿Esto qué relación tiene con la lógica de negocio?

2021-12-07 16:58 UTC, JJ commented on spec/tienda_web_spec.rb
> +        date_predicted = Date.parse(predicted.values.to_s)
¿La predicción es decir que va a haber rebajas la misma fecha que todos los años? ¿De veras que no se te ha ocurrido una lógica de negocio mejor?

2021-12-07 17:12 UTC, Paszser commented on docs/testrunner.md
> +## Elección
He cambiado el formato y añadido un par de apartados, pero los criterios estaban ahí. Si las razones que he dado no las ve suficiente, por favor, dígamelo.

2021-12-07 17:13 UTC, JJ commented on docs/testrunner.md
> +## Elección
No, no están ahí. Comunicas la "elección" sin decir antes ni los criterios para elegirlo ni los criterios de búsqueda, que tienen que ir *antes* de la elección.

2021-12-07 17:18 UTC, Paszser commented on docs/testrunner.md
> +## Elección
Cambiado el orden para comunicar la elección tras la enumeración de los criterios.

2021-12-07 17:20 UTC, Paszser commented on lib/videojuego.rb
>      class Videojuego
Una de las aplicaciones que tendrá el proyecto es que servirá como fuente de información de los propios videojuegos, así como también predecir las próximas rebajas. Es meramente información adicional, pero si usted lo ve innecesario puedo proceder a borrar la clase.

2021-12-07 17:24 UTC, JJ commented on lib/videojuego.rb
>      class Videojuego
Yo no soy quién para verlo innecesario o no. Simplemente te estoy preguntando qué relación tiene con la lógica de negocio.

2021-12-07 17:26 UTC, Paszser commented on spec/tienda_web_spec.rb
> +        date_predicted = Date.parse(predicted.values.to_s)
La lógica de negocio es hacer una predicción teniendo en cuenta datos históricos. Esto sirve como ejemplo de que, incluyendo información de años pasados, se tomará en cuenta la misma para en un futuro tratar de predecir una época. La idea es más adelante, tomar los datos de esas fechas, y hacer una aproximación o media de las más cercanas devolviendo así la próxima época aproximada.

Esto se puede extrapolar a añadir una mayor cantidad de fechas y años, ya sea en una variable hash como esta o un json, pero seguí como se dice en las indicaciones y simplemente traté de implementar parcialmente la lógica, si igualmente lo ve insuficiente puedo tratar de ampliarlo.

2021-12-07 17:27 UTC, Paszser commented on lib/tienda_web.rb
> +            return prediccion_final
La predicción viene dada de la siguiente época más próxima al día actual. De todas formas en el otro comentario review que me dejó se lo explico más detalladamente.

2021-12-07 17:29 UTC, Paszser commented on lib/videojuego.rb
>      class Videojuego
A la lógica de negocio como tal que sería la predicción, no tendría. Como le comenté es algo más adicional para complementar la información y hacerlo más atractivo de cara a un potencial visitante.

2021-12-13 11:02 UTC, Paszser commented
@JJ modificada la implementación de la lógica de negocio y el test. Listo para revisión 😃.

2021-12-13 13:05 UTC, JJ requested changes
Aunquei la lógica de negocio es bastante endeble, todavía tienes que poner una de las partes más importantes de este objetivo.

2021-12-13 13:05 UTC, JJ commented on docs/testrunner.md
> +Por tanto y debido a los criterios citados anteriormente, se ha hecho elección de este framework para realizar los diversos test que involucrarán al proyecto.
Por favor, mira los errores frecuentes en las sesiones de clase. En particular, no se comunica la decisión, sino que se establecen una serie de criterios de búsqueda y requisitos, se muestran cuantas herramientas la cumplen, y se elige una.
Además, no distingues entre test runner y biblioteca de aserciones. No sé si RSpec será los dos, pero incluso así tienes que mostrar que conoces el concepto, y que se ha elegido siguiendo las mejores prácticas en el lenguaje.

2021-12-13 13:05 UTC, JJ commented on lib/tienda_web.rb
> +                    fecha = Time.new(2022, fecha.month, fecha.day)
No se pone ninguna constante en el código, y mucho menos en una función que ni siquiera es el constructor.

2021-12-13 23:42 UTC, Paszser commented on lib/tienda_web.rb
> +                    fecha = Time.new(2022, fecha.month, fecha.day)
Aquí no hay ninguna constante. En Ruby las constantes son variables que empiezan por mayúscula, véase: "Predic = []" por ejemplo. Todo lo que se usa en la función son variables normales y corrientes.

2021-12-13 23:44 UTC, Paszser commented on docs/testrunner.md
> +Por tanto y debido a los criterios citados anteriormente, se ha hecho elección de este framework para realizar los diversos test que involucrarán al proyecto.
Añadido, espero que de la forma que usted pide, tanto el concepto de aserción como al final, en el último párrafo, la decisión de que escojo RSpec.

2021-12-13 23:46 UTC, Paszser commented
@JJ incluidos los cambios para satisfacer las necesidades sobre las bibliotecas de aserciones y comunicar la elección de RSpec.

2021-12-16 10:43 UTC, JJ commented on lib/tienda_web.rb
> +                    fecha = Time.new(2022, fecha.month, fecha.day)
Bueno, un literal. Me refiero al 2022, claro. Perdón.

2021-12-16 10:53 UTC, JJ requested changes
Por favor, dale una vuelta más tanto al código que has hecho como a la presentación de los marcos de pruebae elegidos y por qué los has elegido.

2021-12-16 10:53 UTC, JJ commented on README.md
> +Finalemente como en momentos previos usamos Rake para automatizar el pryecto. Podremos hacer uso del siguiente comando para testear nuestro código:
Dos finalmente...

2021-12-16 10:53 UTC, JJ commented on docs/testrunner.md
> +## RSpec
1. Establecer criterios.
2. Mostrar las opciones existentes
3. Elegir las herramientas más adecuadas según estos criterios.
Además, estamos hablando de dos herramientas: test runner y biblioteca de aserciones. Es importante que distingáis entre las dos. Una búsqueda ligera de test frameworks en Ruby da varios, que ni siquiera mencionas. También bibliotecas de aserciones, que tampoco mencionas. Es imprescindible que aprendáis primero lo necesario para tomar decisiones y luego que justifiquéis esas decisiones para pasar este objetivo.

2021-12-16 10:53 UTC, JJ commented on lib/tienda_web.rb
> +            def prediccion(fechas_rebajas)
¿Por qué esta función recibe muchas fechas y no una sola?

2021-12-16 10:53 UTC, JJ commented on lib/tienda_web.rb
> +                @nombre = nombre
¿Cómo es que los datos que se van a usar para hacer la predicción no forman parte del constructor?

2021-12-17 11:56 UTC, Paszser commented on lib/tienda_web.rb
> +            def prediccion(fechas_rebajas)
Porque la función es la que se encarga de realizar a partir de todas las fechas recogidas históricamente, la predicción de la próxima fecha aproximada de una época de rebajas.

2021-12-17 12:48 UTC, Paszser commented
@JJ ¡Listo para revisión! 😄

2021-12-17 19:10 UTC, JJ commented
Por favor, seguir la convención general para los commits, sólo 50 caracteres en la primera línea.

2021-12-17 19:11 UTC, JJ approved these changes
:+1:

2021-12-18 10:42 UTC, merged